language: go
go_import_path: github.com/agalitsyn/goapi
dist: trusty
sudo: false

go:
  - 1.9

install:
  - go get github.com/alecthomas/gometalinter 
  - gometalinter --install --update

script:
  - make lint
  - make test

notifications:
  email:
    on_success: never
    on_failure: change
