language: go
go_import_path: github.com/agalitsyn/goapi
dist: trusty
sudo: false

go:
  - "1.10"

install:
  - go get -u gopkg.in/alecthomas/gometalinter.v2
  - gometalinter --install --update

script:
  - make lint
  - make test

notifications:
  email:
    on_success: never
    on_failure: change
