version: '3'

services:
  api:
    image: agalitsyn/go-app:latest
    command:
      - api
    environment:
      HTTP_ADDR: 0.0.0.0:8080
      LOG_LEVEL: debug
      LOG_FORMAT: text
      POSTGRES_URL: postgres://go-app:go-app@postgres/go-app?sslmode=disable
    ports:
      - 8080:8080

  postgres:
    image: postgres:12
    volumes:
      - postgres_backup:/data/postgres/backup
      - postgres_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: go-app
      POSTGRES_USER: go-app
      POSTGRES_PASSWORD: go-app
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 55432:5432
    restart: unless-stopped

volumes:
  postgres_backup: {}
  postgres_data: {}
